services:
  app:
    # dockerfile: ./Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "2004:2004"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=ecommerce
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    ports:
      - "54327:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:
    driver: local
